---
name: phpreleaser

# Grant GITHUB_TOKEN the rights it needs
permissions:
  contents: write # gives access to create Releases via the REST API
  issues: write # optional, if you want to comment on PRs/issues
  pull-requests: write # optional, same
  packages: write # optional, if you publish packages

on:
  pull_request:
  push:
    tags:
      - "*"

jobs:
  phpreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Update Version in PHP file
        run: |
          sed -i "s/^\\( \\* Version: \\).*/\\1${{ github.ref_name }}/" woocommerce-payment-gateway-app.php

      - name: Print Release Version
        run: echo "Release version is ${{ github.ref_name }}"

      - name: Create Subfolder
        run: |
          mkdir -p woocommerce-payment-gateway-app
          find . -maxdepth 1 -type f \
            -exec mv {} woocommerce-payment-gateway-app/ \;
          find . -maxdepth 1 -type d ! -name woocommerce-payment-gateway-app ! -name . \
            -exec mv {} woocommerce-payment-gateway-app/ \;
          rm -rf woocommerce-payment-gateway-app/.git* woocommerce-payment-gateway-app/.github

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: "zip"
          filename: woocommerce-payment-gateway-app_v${{ github.ref_name }}.zip
          exclusions: "woocommerce-payment-gateway-app/RELEASE.md *.git* *.github*"

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: woocommerce-payment-gateway-app_v${{ github.ref_name }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
